[Enhancement] Update document contents
ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator pull request #115
Opened 2024-03-28 11:48 UTC by dutt0

## Overview/Summary
This pull request updates the following to the newest and also adds FR content
- CONTRIBUTING.md
- LICENSE 
- SECURITY.md
- SUPPORT.md
- Code of Conduct 

## This PR fixes/adds/changes/removes
N/A

### Breaking Changes
N/A

## Testing Evidence
N/A

## As part of this Pull Request I have

- [x] Checked for duplicate [Pull Requests](https://github.com/ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator/pulls)
- [x] Associated it with relevant [GitHub Issues](https://github.com/ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator/issues)
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator/tree/main)
- [ ] Performed testing and provided evidence.
- [x] Updated relevant and associated documentation.
- [x] Ensure PowerShell module versions have been updated (manually or with the ./tools/Update-ModuleVersions.ps1 script)

2024-04-02 13:54 UTC, MathesonSho commented on LICENSE
Keep the original Microsoft MIT License - we're just adding ours as well.

2024-04-02 13:56 UTC, MathesonSho requested changes
License file- let's keep the original MS License.

2024-04-02 15:13 UTC, dutt0 commented on LICENSE
Ok. Putting back to original Microsoft MIT License content.

2024-04-03 14:35 UTC, alalvi00 approved these changes

2024-04-03 14:36 UTC, MathesonSho approved these changes

2024-04-03 18:49 UTC, merged