Gsingh/gr2 val6 checkonlineattackcountermeasures
ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator pull request #203
Opened 2024-09-17 15:55 UTC by singhgss

## Overview/Summary

Replace this with a brief description of what this Pull Request fixes, changes, etc.

## This PR fixes/adds/changes/removes

1. *Replace me*
2. *Replace me*
3. *Replace me*

### Breaking Changes

1. *Replace me*
2. *Replace me*

## Testing Evidence

Please provide any testing evidence to show that your Pull Request works/fixes as described and planned (include screenshots, if appropriate).

## As part of this Pull Request I have

- [ ] Checked for duplicate [Pull Requests](https://github.com/ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator/pulls)
- [ ] Associated it with relevant [GitHub Issues](https://github.com/ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator/issues)
- [ ] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator/tree/main)
- [ ] Performed testing and provided evidence.
- [ ] Updated relevant and associated documentation.
- [ ] Ensure PowerShell module versions have been updated (manually or with the ./tools/Update-ModuleVersions.ps1 script)

2024-09-25 12:38 UTC, dutt0 commented on src/GUARDRAIL 2 MANAGE ACCESS/Audit/Check-OnlineAttackCountermeasures.psd1
Need to update the commented lines for this file (module manifest and date)

2024-09-25 12:54 UTC, dutt0 requested changes

2024-09-25 12:54 UTC, dutt0 commented on src/GUARDRAIL 2 MANAGE ACCESS/Audit/Check-OnlineAttackCountermeasures.psm1
Do we need the ItemName hardcoded here in the param?

2024-09-25 12:54 UTC, dutt0 commented on src/GuardRails-Localization/GR-ComplianceChecks-Msgs.psd1
Instead of including (M) for 'Mandatory' in 'onlineAttackCounterMeasures', we can put  "Required": "True" in modules.json

2024-09-25 12:54 UTC, dutt0 commented on setup/modules.json
This is a mandatory control. We can put  "Required": "True"

2024-09-25 12:54 UTC, dutt0 commented on src/GuardRails-Localization/fr-CA/GR-ComplianceChecks-Msgs.psd1
Instead of including (M) for 'Mandatory' in 'onlineAttackCounterMeasures', we can put "Required": "True" in modules.json

2024-09-25 12:54 UTC, dutt0 commented on setup/main.ps1
Do we need to keep the commented line 231?

2024-09-26 14:21 UTC, singhgss commented on setup/main.ps1
It was there already. I guess we can keep it for ourselves for debugging if we need to just uncomment.

2024-09-26 14:22 UTC, singhgss commented on setup/modules.json
Thanks for catching that.

2024-09-26 14:24 UTC, singhgss commented on src/GUARDRAIL 2 MANAGE ACCESS/Audit/Check-OnlineAttackCountermeasures.psm1
Not needed, this was for testing/debugging

2024-09-27 16:12 UTC, dutt0 approved these changes
LGTM

2024-09-27 17:43 UTC, alalvi00 approved these changes

2024-09-27 17:44 UTC, merged