Created a new control in GR1 based on GR3 control but with more flexi…
ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator pull request #217
Opened 2024-09-20 20:11 UTC by alalvi00

Created a new control in GR1 based on GR3 control but with more flexibility towards the conditions of CAPs

More conditions will be added later on as we work on this control

## Overview/Summary

Created a new control in Guardrail 1 called Check-CloudAccountsMFA which is based on the control in Guardrail 3. The new control allows more conditions to be checked for the Conditional Access Policies giving a more granular level of MFA check.

## This PR fixes/adds/changes/removes

1. Adds a new control in modules.json
2. A new module in GR1 and psmodules zip

### Breaking Changes

N/A

## Testing Evidence

No testing evidence since it is a copy of GR3 control with the conditions changed.

## As part of this Pull Request I have

- [ ] Checked for duplicate [Pull Requests](https://github.com/ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator/pulls)
- [ ] Associated it with relevant [GitHub Issues](https://github.com/ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator/issues)
- [ ] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator/tree/main)
- [ ] Performed testing and provided evidence.
- [ ] Updated relevant and associated documentation.
- [ ] Ensure PowerShell module versions have been updated (manually or with the ./tools/Update-ModuleVersions.ps1 script)

2024-09-23 11:46 UTC, dutt0 commented on setup/modules.json
Profiles array value is not correct.

2024-09-23 11:57 UTC, dutt0 requested changes
1. Please follow our naming convention for PR title
2. Where is the ItemName for this control? The GR-ComplianceChecks-Msgs are not included in the PR

2024-09-23 13:24 UTC, alalvi00 commented on setup/modules.json
Not sure about this, could you provide the right values?

2024-09-23 13:26 UTC, alalvi00 commented
> 1. Please follow our naming convention for PR title
> 2. Where is the ItemName for this control? The GR-ComplianceChecks-Msgs are not included in the PR


1) Fixed
2) New compliance messages are not needed since it uses the messages from the previous control

2024-09-23 13:38 UTC, dutt0 commented on setup/modules.json
For guardrail1, [1, 2, 3, 4, 5, 6]

2024-09-23 13:42 UTC, dutt0 commented
> > 1. Please follow our naming convention for PR title
> > 2. Where is the ItemName for this control? The GR-ComplianceChecks-Msgs are not included in the PR
> 
> 1. Fixed
> 2. New compliance messages are not needed since it uses the messages from the previous control

2. Please update the ItemName in English and French (in the ticket) for this GR control @alalvi00

2024-09-24 14:19 UTC, singhgss approved these changes
Approved with suggested changes in module.json

2024-09-24 14:19 UTC, singhgss commented on setup/modules.json
> +    "Profiles": [2, 3, 4, 5, 6],
Think @dutt0  was referring to this profile array in modules.json

2024-09-24 14:36 UTC, dutt0 requested changes
Since this is an enhancement on an existing control and new file added to this PR,  we need to remove all the relevant files associated with the existing GR3 'Multi-Factor authentication required for all users by Conditional Access Policy' control

2024-09-27 14:16 UTC, dutt0 approved these changes
LGTM

2024-09-27 14:17 UTC, merged