GR4 Finops Control
ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator pull request #247
Opened 2024-10-18 18:02 UTC by singhgss

## Overview/Summary

Replace this with a brief description of what this Pull Request fixes, changes, etc.

## This PR fixes/adds/changes/removes

1. *Replace me*
2. *Replace me*
3. *Replace me*

### Breaking Changes

1. *Replace me*
2. *Replace me*

## Testing Evidence

Please provide any testing evidence to show that your Pull Request works/fixes as described and planned (include screenshots, if appropriate).

## As part of this Pull Request I have

- [ ] Checked for duplicate [Pull Requests](https://github.com/ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator/pulls)
- [ ] Associated it with relevant [GitHub Issues](https://github.com/ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator/issues)
- [ ] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator/tree/main)
- [ ] Performed testing and provided evidence.
- [ ] Updated relevant and associated documentation.
- [ ] Ensure PowerShell module versions have been updated (manually or with the ./tools/Update-ModuleVersions.ps1 script)

2024-11-25 19:37 UTC, dutt0 requested changes

2024-11-25 19:37 UTC, dutt0 commented on src/GUARDRAIL 4 ENTERPRISE MONITORING ACCOUNTS/Audit/Check-FinOpsToolStatus.psm1
Are these keeping the commented lines?

2024-11-26 15:31 UTC, alalvi00 approved these changes

2024-11-26 15:55 UTC, dutt0 approved these changes

2024-11-26 16:11 UTC, merged