Idutta/gr2 v10 automated role review for guests
ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator pull request #286
Opened 2024-11-29 15:14 UTC by dutt0

## Overview/Summary

Replace this with a brief description of what this Pull Request fixes, changes, etc.

## This PR fixes/adds/changes/removes

1. *Replace me*
2. *Replace me*
3. *Replace me*

### Breaking Changes

1. *Replace me*
2. *Replace me*

## Testing Evidence

Please provide any testing evidence to show that your Pull Request works/fixes as described and planned (include screenshots, if appropriate).

## As part of this Pull Request I have

- [ ] Checked for duplicate [Pull Requests](https://github.com/ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator/pulls)
- [ ] Associated it with relevant [GitHub Issues](https://github.com/ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator/issues)
- [ ] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator/tree/main)
- [ ] Performed testing and provided evidence.
- [ ] Updated relevant and associated documentation.
- [ ] Ensure PowerShell module versions have been updated (manually or with the ./tools/Update-ModuleVersions.ps1 script)

2024-12-09 15:23 UTC, alalvi00 submitted a review, later dismissed

2024-12-09 15:36 UTC, singhgss approved these changes

2024-12-09 18:33 UTC, alalvi00 requested changes
Duplicate function "Expand-ListColumns" found in PR in the file GR-Common https://github.com/ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator/pull/299/files

This is redundant even if they are in different files so it would be better to keep it in GR-Common and remove it from the control file

2024-12-09 19:10 UTC, dutt0 commented
> Duplicate function "Expand-ListColumns" found in PR in the file GR-Common https://github.com/ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator/pull/299/files
> 
> This is redundant even if they are in different files so it would be better to keep it in GR-Common and remove it from the control file

@alalvi00 This PR will be the first one to merge. This is in the process of being fixed in the  https://github.com/ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator/pull/299/files once the main branch will be pulled to that branch.

2024-12-10 14:54 UTC, alalvi00 approved these changes

2024-12-10 19:33 UTC, merged